version: '2'

services:

  bitcored:
    build:
      context: ./docker
      dockerfile: ./Dockerfile.bitcored
    image: explorer-bitcored
    container_name: explorer-bitcored
    command: -rpcuser=rpcuser -rpcpassword=bitcore
    restart: always
    networks:
      explorer-net:
        ipv4_address: 172.21.0.12
    ports:
      - 8555:8555
    expose:
      - 8556
    volumes:
      - ./bitcore:/data 
  
  explorer:
    build:
      context: .
      dockerfile: ./Dockerfile.explorer
    image: btx-explorer
    container_name: btx-explorer 
    restart: always
    networks:
      explorer-net:
        ipv4_address: 172.21.0.13
    ports:
      - 3002:3002
    expose:
      - 3002
    environment:
      - "BTCEXP_INFLUXDB_URI=influx://dbuser:bitcore@172.21.0.10:8086"
      - "BTCEXP_BITCOIND_URI=bitcore://rpcuser:bitcore@172.21.0.12:8556?timeout=50000"
    depends_on:
      - influxdb
      - bitcored

  #https://docs.docker.com/samples/library/influxdb/
  #http://localhost:8086
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    networks:
      explorer-net:
        ipv4_address: 172.21.0.10
    ports:
      - 8083:8083
    expose:
      - 8083
      - 8086
    volumes:
      - influx-storage:/var/lib/influxdb
    environment:
      - "INFLUXDB_ADMIN_ENABLED=true"
      - "INFLUXDB_HTTP_AUTH_ENABLED=false"
      - "INFLUXDB_DB=influxdb"
      - PRE_CREATE_DB="influxdb"
      - "INFLUXDB_ADMIN_USER=dbuser"
      - "INFLUXDB_ADMIN_PASSWORD=bitcore"

  #http:127.0.0.1:8888
  #chronograf:
  #  image: chronograf:latest
  #  container_name: chronograf
  #  restart: always
  #  networks:
  #    explorer-net:
  #      ipv4_address: 172.21.0.14
  #  ports:
  #    - 127.0.0.1:8888:8888
  #  expose:
  #    - 8888
  #  volumes:
  #    - chronograf-storage:/var/lib/chronograf
  #  environment:
  #    - "INFLUXDB_URL=http://172.21.0.10:8086"
  #    - "INFLUXDB_USERNAME=dbuser"
  #    - "INFLUXDB_PASSWORD=bitcore"
  #  command: 
  #    - "--influxdb-url=http://172.21.0.10:8086"
  #  depends_on:
  #    - influxdb
  
  #http://localhost:3000
  #grafana:
  #  image: grafana/grafana:latest
  #  container_name: grafana
  #  restart: always
  #  networks:
  #    explorer-net:
  #      ipv4_address: 172.21.0.15
  #  ports:
  #    - 3000:3000
  #  expose:
  #    - 3000
  #  volumes:
  #    - grafana-storage:/var/lib/grafana
  #    - ./grafana-provisioning/:/etc/grafana/provisioning
  #  environment:
  #    - "GF_SECURITY_ADMIN_USER=dbuser"
  #    - "GF_SECURITY_ADMIN_PASSWORD=bitcore"
  #  depends_on:
  #    - influxdb

volumes:
  influx-storage:
  #chronograf-storage:
  #grafana-storage:

networks:
  explorer-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24
